name: Metrics

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 0' # Weekly on Sunday at midnight UTC

jobs:
  generate-metrics:
    runs-on: ubuntu-latest
    environment:
      name: production
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          plugin_base: yes
          base: repositories

          plugin_lines: yes
          plugin_lines_sections: base, repositories, history
          plugin_lines_repositories_limit: 4
          plugin_lines_history_limit: 1
          plugin_lines_delay: 30

          plugin_languages: yes
          plugin_languages_ignored: html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell, gnuplot
          plugin_languages_limit: 4
          plugin_languages_details: lines, bytes-size, percentage
          plugin_languages_aliases: javascript:JS, typescript:TS
          plugin_languages_colors: rainbow
          plugin_languages_sections: most-used,recently-used
