name: Metrics
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 0' # Weekly on Sunday at midnight UTC
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment:
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          
          # -------------------
          # Base configuration
          # -------------------
          base: repositories
          
          # -------------------
          # Isometric Calendar plugin
          # -------------------
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          
          # -------------------
          # Lines of Code plugin
          # -------------------
          plugin_lines: yes
          plugin_lines_sections: base, repositories, history
          plugin_lines_repositories_limit: 4
          plugin_lines_history_limit: 1
          plugin_lines_delay: 30
          
          # -------------------
          # Languages plugin
          # -------------------
          plugin_languages: yes
          plugin_languages_ignored: html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell, gnuplot
          plugin_languages_limit: 4
          plugin_languages_details: lines, bytes-size, percentage
          plugin_languages_aliases: javascript:JS, typescript:TS
          plugin_languages_colors: rainbow
          plugin_languages_sections: most-used, recently-used
          plugin_languages_indepth: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_analysis_timeout_repositories: 7.5
          plugin_languages_categories: markup, programming
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_load: 300
          plugin_languages_recent_days: 14
